import express from "express";
import dotenv from "dotenv";
import OpenAI from "openai";
import multer from "multer";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import pdf from "pdf-parse";
import mammoth from "mammoth";
import XLSX from "xlsx";
import { fileURLToPath } from "url";
import { execFile } from "child_process";

dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const port = process.env.PORT || 3000;
const version = "9.0.5";
const key = process.env.OPENAI_API_KEY || "";
const client = new OpenAI({ apiKey: key, timeout: Number(process.env.AMX_CHAT_TIMEOUT_MS || 120000), maxRetries: 0 });
const dataRoot = process.env.AMX_DATA_DIR ? path.resolve(process.env.AMX_DATA_DIR) : __dirname;
const abs = p => path.join(dataRoot,p);
function seedDataRoot(){if(dataRoot===__dirname)return; fs.mkdirSync(dataRoot,{recursive:true}); for(const item of ["data","COOPERATIVAS","BIBLIOTECA-AMX","knowledge","logs","config","uploads"]){const src=path.join(__dirname,item),dest=abs(item); if(fs.existsSync(src)&&!fs.existsSync(dest))fs.cpSync(src,dest,{recursive:true})} for(const item of ["data","COOPERATIVAS","knowledge","logs","config","uploads"])fs.mkdirSync(abs(item),{recursive:true})}
seedDataRoot();
app.use(express.json({ limit: "20mb" }));
const upload = multer({ dest: abs("uploads"), limits: { fileSize: 25 * 1024 * 1024 } });
const P = { coops:"data/cooperativas.json", notas:"data/notas.json", dna:"data/dna.json", pend:"data/pendencias.json", timeline:"data/timeline.json", usage:"logs/ai-usage.json", budget:"config/budget.json" };
const dataKeys = { cooperativas:P.coops, notas:P.notas, dna:P.dna, pendencias:P.pend, timeline:P.timeline, usage:P.usage, budget:P.budget };
const levels = { economica:{label:"Econômica",model:"gpt-4.1-mini",i:.4,o:1.6}, intermediaria:{label:"Intermediária",model:"gpt-4.1",i:2,o:8}, avancada:{label:"Avançada",model:"gpt-4.1",i:2,o:8}, maximo:{label:"Máximo",model:"gpt-4.1",i:2,o:8} };
function rj(p,d){try{return fs.existsSync(abs(p))?JSON.parse(fs.readFileSync(abs(p),"utf-8")||JSON.stringify(d)):d}catch{return d}}
let suppressDataBackup=false;
function wj(p,d){if(!suppressDataBackup&&Object.values(dataKeys).includes(p))autoBackup("antes-"+path.basename(p,".json"));fs.mkdirSync(path.dirname(abs(p)),{recursive:true});fs.writeFileSync(abs(p),JSON.stringify(d,null,2),"utf-8")}
function stamp(){return new Date().toISOString().replace(/[:.]/g,"-").slice(0,19)}
function dataSnapshot(reason="manual"){const data={}; for(const [k,p] of Object.entries(dataKeys))data[k]=rj(p,k==="dna"||k==="budget"?{}:[]); return {app:"AMX HUB",version,createdAt:new Date().toISOString(),reason,data}}
function writeSnapshot(reason){const out=abs(`BACKUPS/dados-amx-hub-${stamp()}-${safe(reason)}.json`); fs.mkdirSync(path.dirname(out),{recursive:true}); fs.writeFileSync(out,JSON.stringify(dataSnapshot(reason),null,2),"utf-8"); return out}
function autoBackup(reason){try{return path.relative(dataRoot,writeSnapshot(reason))}catch(e){console.error("Falha no backup automatico:",e.message); return null}}
function restoreSnapshot(payload){const src=payload?.data?payload.data:payload; if(!src||typeof src!=="object")throw new Error("Arquivo de backup invalido."); autoBackup("antes-importar-dados"); suppressDataBackup=true; try{for(const [k,p] of Object.entries(dataKeys)){if(Object.prototype.hasOwnProperty.call(src,k))wj(p,src[k])}}finally{suppressDataBackup=false} rj(P.coops,[]).forEach(ensureCoop); return {ok:true,summary:summary()}}
function safe(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._ -]/g,"").trim()}
function slug(s){return safe(s).toLowerCase().replace(/\s+/g,"-")}
function agentFrom(nome){return safe(String(nome||"").replace(/^Sicoob\s+/i,"")).replace(/\s+/g,"-")}
function dirs(d){const p=abs(d);return fs.existsSync(p)?fs.readdirSync(p,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name).sort():[]}
function readTexts(d){const p=abs(d); if(!fs.existsSync(p))return""; let out=""; for(const e of fs.readdirSync(p,{withFileTypes:true})){const f=path.join(p,e.name); if(e.isDirectory())out+=readTexts(path.relative(dataRoot,f)); else if([".txt",".md",".csv",".json"].includes(path.extname(e.name).toLowerCase())) out+=`\n\n===== ${path.relative(dataRoot,f)} =====\n`+fs.readFileSync(f,"utf-8");} return out}
function ensureCoop(c){if(!c?.agentKey)return; const root=abs("COOPERATIVAS/"+c.agentKey); ["Dados-Gerais","Bloco-de-Notas","DNA","Pendencias","Timeline","Arquivos","Atas","Cronogramas","Relatorios","Indicadores","IA"].forEach(s=>fs.mkdirSync(path.join(root,s),{recursive:true})); fs.writeFileSync(path.join(root,"Dados-Gerais","dados-gerais.json"),JSON.stringify(c,null,2),"utf-8"); const legacy=abs("knowledge/ANALISTA-AMX/"+c.agentKey); ["cronogramas","atas","relatorios","anexos"].forEach(s=>fs.mkdirSync(path.join(legacy,s),{recursive:true})); fs.writeFileSync(path.join(legacy,"base.txt"),`ANALISTA ${c.nome.toUpperCase()} — BASE AMX\n\nSistema: ${c.sistema||""}\nProduto(s): ${(c.produtos||[]).join(", ")}\nStatus: ${c.status||""}\n\nObservações:\n${c.observacoes||""}`,"utf-8")}
function summary(){const c=rj(P.coops,[]),s={},p={}; let avg=0; c.forEach(x=>{s[x.sistema]=(s[x.sistema]||0)+1;(x.produtos||[]).forEach(y=>p[y]=(p[y]||0)+1);avg+=Number(x.evolucao||0)}); return {total:c.length,sistemas:s,produtos:p,evolucaoMedia:c.length?Math.round(avg/c.length):0}}
function timeline(agentKey,nome,tipo,titulo,descricao){const all=rj(P.timeline,[]); const item={id:"timeline-"+Date.now(),agentKey,cooperativaNome:nome||"",tipo,titulo,descricao,data:new Date().toISOString().slice(0,10),createdAt:new Date().toISOString()}; all.push(item); wj(P.timeline,all); if(agentKey){const dir=abs("COOPERATIVAS/"+agentKey+"/Timeline");fs.mkdirSync(dir,{recursive:true});fs.appendFileSync(path.join(dir,"timeline.md"),`\n\n## ${item.data} — ${tipo}\n**${titulo}**\n\n${descricao||""}\n`,"utf-8")} return item}
function getDNA(a){return rj(P.dna,{})[a]||{}}
function context(a){const coops=rj(P.coops,[]),dna=rj(P.dna,{}),pendencias=rj(P.pend,[]),eventos=rj(P.timeline,[]),notas=rj(P.notas,[]),global=!a||a==="automatico"||a==="geral"; if(global)return {cooperativas:coops,dna,pendencias:pendencias.filter(p=>p.status!=="Concluída"),timeline:eventos.slice(-30).reverse(),notas:notas.slice(-30).reverse()}; return {cooperativa:coops.find(c=>c.agentKey===a)||{},dna:dna[a]||{},pendencias:pendencias.filter(p=>p.agentKey===a&&p.status!=="Concluída"),timeline:eventos.filter(t=>t.agentKey===a).slice(-10).reverse(),notas:notas.filter(n=>n.agentKey===a).slice(-10).reverse()}}
function noteDir(n){return abs("COOPERATIVAS/"+n.agentKey+"/Bloco-de-Notas")}
function findNoteFile(n){const dir=noteDir(n); if(!fs.existsSync(dir))return""; return fs.readdirSync(dir).find(name=>name.endsWith(".md")&&name.includes(n.id))||""}
function writeNoteFile(n,previous){const dir=noteDir(n); fs.mkdirSync(dir,{recursive:true}); const old=findNoteFile(previous||n),name=`${n.dataInteracao}-${safe(n.titulo).replace(/\s+/g,"-")}-${n.id}.md`; if(old&&old!==name)fs.rmSync(path.join(dir,old),{force:true}); fs.writeFileSync(path.join(dir,name),`# ${n.titulo}\n\nCooperativa: ${n.cooperativaNome}\nData: ${n.dataInteracao}\nDestino: ${n.destino}\n\n${n.anotacao}\n\nArquivos:\n${(n.arquivos||[]).join("\n")}`,"utf-8")}
function deleteNoteFile(n){const file=findNoteFile(n); if(file)fs.rmSync(path.join(noteDir(n),file),{force:true})}
function knowledge(a,folder){let out=readTexts("BIBLIOTECA-AMX"); if(a&&a!=="automatico"&&a!=="geral"){out+=readTexts("knowledge/ANALISTA-AMX/"+a)+readTexts("COOPERATIVAS/"+a)}else out+=readTexts("knowledge/ANALISTA-AMX"); if(folder)out+=readTexts("knowledge/"+folder); return out.slice(0,220000)}
function choose(l,msg,has){if(l&&l!=="automatica"&&levels[l])return l; const t=String(msg||"").toLowerCase(); if(has)return"avancada"; if(["parecer","diagnóstico","diagnostico","diretoria","conselho","planejamento"].some(x=>t.includes(x)))return"maximo"; if(["ata","cronograma","relatório","relatorio","plano de ação","plano de acao"].some(x=>t.includes(x)))return"intermediaria"; return"economica"}
function estimate(u,l){const v=levels[l]||levels.intermediaria,inp=u?.input_tokens||u?.prompt_tokens||0,out=u?.output_tokens||u?.completion_tokens||0; return {totalTokens:inp+out,costBrl:+(((inp/1e6*v.i+out/1e6*v.o)*5.5).toFixed(4))}}
function usageSummary(){const logs=rj(P.usage,[]),today=new Date().toISOString().slice(0,10),month=today.slice(0,7),sum=a=>+a.reduce((x,l)=>x+Number(l.costBrl||0),0).toFixed(2),td=logs.filter(l=>String(l.date).startsWith(today)),mo=logs.filter(l=>String(l.date).startsWith(month)); return {today:sum(td),month:sum(mo),total:sum(logs),countToday:td.length,countMonth:mo.length,budget:rj(P.budget,{})}}
function isImg(f){return [".png",".jpg",".jpeg",".webp"].includes(path.extname(f.originalname||"").toLowerCase())}
function imgUrl(f){const ext=path.extname(f.originalname||"").toLowerCase(),mime=ext===".png"?"image/png":ext===".webp"?"image/webp":"image/jpeg"; return `data:${mime};base64,${fs.readFileSync(f.path).toString("base64")}`}
async function extract(f){const ext=path.extname(f.originalname||"").toLowerCase(),buf=fs.readFileSync(f.path); try{if(ext===".pdf")return (await pdf(buf)).text||""; if(ext===".docx")return (await mammoth.extractRawText({buffer:buf})).value||""; if(ext===".xlsx"||ext===".xls"){const wb=XLSX.read(buf,{type:"buffer"});return wb.SheetNames.map(n=>`\n\nABA: ${n}\n${XLSX.utils.sheet_to_csv(wb.Sheets[n])}`).join("")} if([".txt",".csv",".json",".md"].includes(ext))return buf.toString("utf-8"); if(isImg(f))return`[Imagem ${f.originalname} anexada.]`; return`[Arquivo ${f.originalname} anexado.]`}catch(e){return`[Erro ao ler ${f.originalname}: ${e.message}]`}}
function premium(msg){const t=String(msg||"").toLowerCase(); if(t.includes("cronograma"))return"Entregue em formato de cronograma executivo com tabela."; if(t.includes("ata"))return"Entregue como ata executiva."; if(t.includes("parecer")||t.includes("diagnóstico")||t.includes("diagnostico"))return"Entregue como parecer executivo."; if(t.includes("email")||t.includes("e-mail"))return"Entregue apenas o e-mail pronto, com assunto sugerido."; return"Use títulos, listas claras e linguagem executiva AMX."}
const authFlag=String(process.env.AMX_AUTH_ENABLED||"").toLowerCase();
const authEnabled=authFlag==="true"||(!authFlag&&process.env.NODE_ENV==="production")||(!authFlag&&Boolean(process.env.AMX_ADMIN_PASSWORD));
const adminUser=process.env.AMX_ADMIN_USER||"admin";
const adminPass=process.env.AMX_ADMIN_PASSWORD||"";
const sessionSecret=process.env.AMX_SESSION_SECRET||adminPass||key||"amx-hub-local-session";
const sessionHours=Number(process.env.AMX_SESSION_HOURS||12);
function cookieMap(req){return Object.fromEntries(String(req.headers.cookie||"").split(";").map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf("=");return i<0?[x,""]:[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}))}
function b64(v){return Buffer.from(v).toString("base64url")}
function sign(v){return crypto.createHmac("sha256",sessionSecret).update(v).digest("base64url")}
function safeEqual(a,b){const aa=Buffer.from(String(a)),bb=Buffer.from(String(b)); return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)}
function makeSession(user){const payload=b64(JSON.stringify({user,exp:Date.now()+sessionHours*60*60*1000,nonce:crypto.randomUUID()})); return `${payload}.${sign(payload)}`}
function readSession(req){try{const token=cookieMap(req).amx_session||"",[payload,sig]=token.split("."); if(!payload||!sig||!safeEqual(sig,sign(payload)))return null; const data=JSON.parse(Buffer.from(payload,"base64url").toString("utf-8")); if(!data.exp||Date.now()>data.exp)return null; return data}catch{return null}}
function setSessionCookie(res,token){const secure=String(process.env.AMX_COOKIE_SECURE||"").toLowerCase()==="true"||(process.env.NODE_ENV==="production"&&String(process.env.AMX_COOKIE_SECURE||"").toLowerCase()!=="false"); res.setHeader("Set-Cookie",`amx_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${sessionHours*60*60}${secure?"; Secure":""}`)}
function clearSessionCookie(res){res.setHeader("Set-Cookie","amx_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0")}
function loginHtml(){return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AMX HUB - Login</title><style>:root{--navy:#031E34;--teal:#00A6A6;--green:#18B875;--bg:#F5F8FB;--muted:#64748B}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:linear-gradient(135deg,var(--navy),#052C4A);font-family:Arial,Helvetica,sans-serif;color:#10213D}.card{width:min(420px,92vw);background:#fff;border-radius:24px;padding:30px;box-shadow:0 24px 60px rgba(0,0,0,.22)}img{width:210px;display:block;margin:0 auto 18px}h1{margin:0 0 8px;color:var(--navy)}p{color:var(--muted)}input,button{width:100%;border-radius:14px;padding:13px;font-size:15px}input{border:1px solid #DFE8F0;margin:8px 0 12px}button{border:0;background:linear-gradient(135deg,var(--teal),var(--green));color:#fff;font-weight:bold;cursor:pointer}.msg{min-height:22px;margin-top:12px;color:#b91c1c;font-size:13px}</style></head><body><form class="card" id="loginForm"><img src="/logo-amx-coop.png" alt="AMX"><h1>Entrar no AMX HUB</h1><p>Acesso protegido para ambiente online.</p><input id="usuario" autocomplete="username" placeholder="Usuário" value="${adminUser==="admin"?"admin":""}"><input id="senha" type="password" autocomplete="current-password" placeholder="Senha"><button>Entrar</button><div class="msg" id="msg"></div></form><script>document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('msg');msg.textContent='Validando...';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuario:usuario.value,senha:senha.value})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Acesso negado');location.href='/'}catch(err){msg.textContent=err.message}})</script></body></html>`}
app.get("/login",(req,res)=>authEnabled&&readSession(req)?res.redirect("/"):res.send(loginHtml()));
app.get("/api/session",(req,res)=>res.json({authEnabled,authenticated:!authEnabled||Boolean(readSession(req)),user:readSession(req)?.user||null}));
app.post("/api/login",(req,res)=>{if(!authEnabled)return res.json({ok:true,authEnabled:false}); if(!adminPass)return res.status(500).json({error:"AMX_ADMIN_PASSWORD não configurada no servidor."}); const user=String(req.body?.usuario||""),pass=String(req.body?.senha||""); if(user!==adminUser||!safeEqual(pass,adminPass))return res.status(401).json({error:"Usuário ou senha inválidos."}); setSessionCookie(res,makeSession(user)); res.json({ok:true})});
app.post("/api/logout",(req,res)=>{clearSessionCookie(res); res.json({ok:true})});
app.use((req,res,next)=>{if(!authEnabled)return next(); if(["/login","/api/login","/api/logout","/api/session","/api/health","/logo-amx-coop.png","/favicon.ico"].includes(req.path))return next(); if(readSession(req))return next(); if(req.path.startsWith("/api/"))return res.status(401).json({error:"Sessão expirada. Faça login novamente."}); return res.redirect("/login")});
app.get("/api/health",(req,res)=>res.json({ok:true,version,message:`AMX HUB ${version} STABLE funcionando`,hasKey:Boolean(key&&!key.includes("COLE_SUA_CHAVE")&&key.startsWith("sk-")),authEnabled,dataRootConfigured:dataRoot!==__dirname}));
app.get("/api/config",(req,res)=>res.json({agents:[{key:"automatico",label:"Identificar automaticamente"},{key:"geral",label:"Agente Geral AMX"},...dirs("knowledge/ANALISTA-AMX").map(n=>({key:n,label:`Analista ${n.replaceAll("-"," ")}`}))],folders:dirs("knowledge").map(n=>({key:n,label:n.replaceAll("-"," ")}))}));
app.get("/api/cooperativas",(req,res)=>res.json({cooperativas:rj(P.coops,[]),summary:summary()}));
app.post("/api/cooperativas",(req,res)=>{const b=req.body||{},nome=String(b.nome||"").trim(); if(!nome)return res.status(400).json({error:"Nome obrigatório."}); const all=rj(P.coops,[]),id=b.id||slug(nome.replace(/^Sicoob\s+/i,"")),agentKey=b.agentKey||agentFrom(nome); const c={id,nome,sistema:b.sistema||"Crediminas",produtos:Array.isArray(b.produtos)?b.produtos:[],dataInicio:b.dataInicio||"",evolucao:Number(b.evolucao||0),status:b.status||"Ativo",presidente:b.presidente||"",diretor:b.diretor||"",gestor:b.gestor||"",rh:b.rh||"",ti:b.ti||"",marketing:b.marketing||"",observacoes:b.observacoes||"",agentKey}; const i=all.findIndex(x=>x.id===id); i>=0?all[i]=c:all.push(c); wj(P.coops,all); ensureCoop(c); timeline(agentKey,nome,"Cooperativa","Cadastro salvo","Dados salvos."); res.json({ok:true,cooperativa:c,summary:summary()})});
app.put("/api/cooperativas/:id",(req,res)=>{const all=rj(P.coops,[]),i=all.findIndex(c=>c.id===req.params.id); if(i<0)return res.status(404).json({error:"Não encontrada."}); const c={...all[i],...req.body}; c.evolucao=Number(c.evolucao||0); if(!Array.isArray(c.produtos))c.produtos=[]; if(!c.agentKey)c.agentKey=agentFrom(c.nome); all[i]=c; wj(P.coops,all); ensureCoop(c); timeline(c.agentKey,c.nome,"Cooperativa","Cadastro editado","Dados atualizados."); res.json({ok:true,cooperativa:c,summary:summary()})});
app.delete("/api/cooperativas/:id",(req,res)=>{wj(P.coops,rj(P.coops,[]).filter(c=>c.id!==req.params.id)); res.json({ok:true,summary:summary()})});
app.get("/api/notas",(req,res)=>{const a=req.query.agentKey,all=rj(P.notas,[]); res.json({notas:(a?all.filter(n=>n.agentKey===a):all).slice().reverse()})});
app.post("/api/notas",upload.array("files",5),(req,res)=>{const b=req.body||{},agentKey=String(b.agentKey||"").trim(); if(!agentKey)return res.status(400).json({error:"Selecione uma cooperativa."}); if(!String(b.anotacao||"").trim())return res.status(400).json({error:"A anotação não pode ficar vazia."}); const nota={id:"nota-"+Date.now(),agentKey,cooperativaNome:b.cooperativaNome||"",titulo:b.titulo||"Reunião presencial",dataInteracao:b.dataInteracao||new Date().toISOString().slice(0,10),destino:b.destino||"Relatório futuro",anotacao:b.anotacao||"",arquivos:[],createdAt:new Date().toISOString()}; const dir=noteDir(nota),fileDir=path.join(dir,"Arquivos"); fs.mkdirSync(fileDir,{recursive:true}); for(const f of req.files||[]){const dest=path.join(fileDir,`${nota.id}-${safe(f.originalname)}`); fs.copyFileSync(f.path,dest); fs.rmSync(f.path,{force:true}); nota.arquivos.push(path.relative(dataRoot,dest))} const all=rj(P.notas,[]); all.push(nota); wj(P.notas,all); writeNoteFile(nota); timeline(agentKey,nota.cooperativaNome,"Nota",nota.titulo,nota.destino); res.json({ok:true,nota})});
app.put("/api/notas/:id",(req,res)=>{const all=rj(P.notas,[]),i=all.findIndex(n=>n.id===req.params.id); if(i<0)return res.status(404).json({error:"Nota não encontrada."}); const previous=all[i],nota={...previous,...req.body,id:previous.id,agentKey:previous.agentKey,arquivos:previous.arquivos||[],updatedAt:new Date().toISOString()}; if(!String(nota.anotacao||"").trim())return res.status(400).json({error:"A anotação não pode ficar vazia."}); all[i]=nota; wj(P.notas,all); writeNoteFile(nota,previous); timeline(nota.agentKey,nota.cooperativaNome,"Nota atualizada",nota.titulo,nota.destino); res.json({ok:true,nota})});
app.delete("/api/notas/:id",(req,res)=>{const all=rj(P.notas,[]),nota=all.find(n=>n.id===req.params.id); if(!nota)return res.status(404).json({error:"Nota não encontrada."}); wj(P.notas,all.filter(n=>n.id!==req.params.id)); deleteNoteFile(nota); timeline(nota.agentKey,nota.cooperativaNome,"Nota excluída",nota.titulo,"Registro removido do Bloco de Notas.");res.json({ok:true})});
app.get("/api/copilot/:agentKey",(req,res)=>res.json(context(req.params.agentKey)));
app.post("/api/dna/:agentKey",(req,res)=>{const all=rj(P.dna,{}); all[req.params.agentKey]={...(all[req.params.agentKey]||{}),...req.body,agentKey:req.params.agentKey,updatedAt:new Date().toISOString()}; wj(P.dna,all); timeline(req.params.agentKey,req.body.cooperativaNome||"","DNA","DNA atualizado","Informações estratégicas salvas."); res.json({ok:true,dna:all[req.params.agentKey]})});
app.get("/api/pendencias",(req,res)=>{const a=req.query.agentKey,all=rj(P.pend,[]); res.json({pendencias:a?all.filter(p=>p.agentKey===a):all})});
app.post("/api/pendencias",(req,res)=>{const b=req.body||{}; if(!b.agentKey||!b.item)return res.status(400).json({error:"Cooperativa e item são obrigatórios."}); const all=rj(P.pend,[]),item={id:"pend-"+Date.now(),agentKey:b.agentKey,cooperativaNome:b.cooperativaNome||"",item:b.item,responsavel:b.responsavel||"",prazo:b.prazo||"",status:b.status||"Aberta",createdAt:new Date().toISOString()}; all.push(item); wj(P.pend,all); timeline(item.agentKey,item.cooperativaNome,"Pendência",item.item,`Responsável: ${item.responsavel||"-"} | Prazo: ${item.prazo||"-"}`); res.json({ok:true,pendencia:item})});
app.put("/api/pendencias/:id",(req,res)=>{const all=rj(P.pend,[]),i=all.findIndex(p=>p.id===req.params.id); if(i<0)return res.status(404).json({error:"Pendência não encontrada."}); all[i]={...all[i],...req.body,updatedAt:new Date().toISOString()}; wj(P.pend,all); timeline(all[i].agentKey,all[i].cooperativaNome,"Pendência atualizada",all[i].item,`Status: ${all[i].status}`); res.json({ok:true,pendencia:all[i]})});
app.delete("/api/pendencias/:id",(req,res)=>{wj(P.pend,rj(P.pend,[]).filter(p=>p.id!==req.params.id));res.json({ok:true})});
app.get("/api/timeline",(req,res)=>{const a=req.query.agentKey,all=rj(P.timeline,[]);res.json({timeline:(a?all.filter(t=>t.agentKey===a):all).slice().reverse()})});
app.post("/api/generate-from-note",(req,res)=>{const n=rj(P.notas,[]).find(x=>x.id===req.body.noteId); if(!n)return res.status(404).json({error:"Nota não encontrada."}); const tipo=req.body.tipo||n.destino||"Relatório",prompt=`Com base na anotação abaixo, gere um ${tipo} no padrão AMX Coop.\n\nCOOPERATIVA: ${n.cooperativaNome}\nDATA: ${n.dataInteracao}\nANOTAÇÃO:\n${n.anotacao}`; timeline(n.agentKey,n.cooperativaNome,"Geração solicitada",tipo,"Documento solicitado a partir de nota."); res.json({ok:true,prompt,agentKey:n.agentKey})});
app.get("/api/backup/export",(req,res)=>{const file=`dados-amx-hub-${stamp()}.json`; res.setHeader("Content-Disposition",`attachment; filename="${file}"`); res.type("application/json").send(JSON.stringify(dataSnapshot("exportacao-manual"),null,2))});
app.post("/api/backup/import",upload.single("backup"),(req,res)=>{try{if(!req.file)return res.status(400).json({error:"Envie um arquivo de backup JSON."}); const payload=JSON.parse(fs.readFileSync(req.file.path,"utf-8")); fs.rmSync(req.file.path,{force:true}); res.json(restoreSnapshot(payload))}catch(e){if(req.file?.path)fs.rmSync(req.file.path,{force:true}); res.status(400).json({error:e.message||"Nao consegui importar o backup."})}});
app.get("/api/usage",(req,res)=>res.json({logs:rj(P.usage,[]).slice(-100).reverse(),summary:usageSummary()}));
app.post("/api/backup",(req,res)=>{const stamp=new Date().toISOString().replace(/[:.]/g,"-").slice(0,19),ext=process.platform==="win32"?"zip":"tar.gz",out=abs(`BACKUPS/backup-amx-hub-${stamp}.${ext}`),folders=["data","COOPERATIVAS","BIBLIOTECA-AMX","knowledge","logs","config","uploads"].filter(p=>fs.existsSync(abs(p))); fs.mkdirSync(path.dirname(out),{recursive:true}); const done=err=>err?res.status(500).json({error:"Não consegui gerar o backup automático.",details:err.message}):res.json({ok:true,backup:path.relative(dataRoot,out),download:"/api/backups/"+path.basename(out)}); if(process.platform==="win32"){const paths=folders.map(p=>`"${p.replaceAll('"','""')}"`).join(","),cmd=`Compress-Archive -Path ${paths} -DestinationPath "${out.replaceAll('"','""')}" -Force`; return execFile("powershell.exe",["-NoProfile","-Command",cmd],{cwd:dataRoot},done)} execFile("tar",["-czf",out,...folders],{cwd:dataRoot},done)});
app.get("/api/backups/:file",(req,res)=>{const file=path.basename(req.params.file),full=abs("BACKUPS/"+file); if(!fs.existsSync(full))return res.status(404).json({error:"Backup não encontrado."}); res.download(full)});
app.post("/api/chat",upload.array("files",5),async(req,res)=>{try{const msg=String(req.body.message||"").trim(),agent=String(req.body.agent||"automatico"),folder=String(req.body.folder||"ANALISTA-AMX"),reqLevel=String(req.body.aiLevel||"automatica"); if(!key||key.includes("COLE_SUA_CHAVE")||!key.startsWith("sk-"))return res.status(500).json({error:"OPENAI_API_KEY não configurada no .env."}); const files=req.files||[]; if(!msg&&!files.length)return res.status(400).json({error:"Mensagem vazia."}); let anexos=""; for(const f of files)anexos+=`\n\n===== ANEXO: ${f.originalname} =====\n${(await extract(f)).slice(0,60000)}`; const lvlKey=choose(reqLevel,msg,files.length>0),lvl=levels[lvlKey],model=process.env.OPENAI_MODEL||lvl.model; const system=`Você é ${agent==="automatico"?"Assistente AMX HUB":`Analista ${agent.replaceAll("-"," ")}`}, consultor executivo da AMX Coop.\n\nREGRAS:\n- Responda em português do Brasil.\n- Tom executivo, objetivo e consultivo.\n- ${premium(msg)}\n- Use DNA, Pendências, Timeline, Bloco de Notas, Base AMX e anexos.\n\nCONTEXTO DA COOPERATIVA:\n${JSON.stringify(context(agent),null,2)}\n\nBASE AMX:\n${knowledge(agent,folder)}\n\nANEXOS:\n${anexos||"Nenhum anexo."}`; const content=[{type:"input_text",text:msg||"Analise os anexos."}]; for(const f of files)if(isImg(f))content.push({type:"input_image",image_url:imgUrl(f)}); const resp=await client.responses.create({model,input:[{role:"system",content:system},{role:"user",content}]}); const c=estimate(resp.usage||{},lvlKey),log={date:new Date().toISOString(),agent,folder,levelLabel:lvl.label,model,totalTokens:c.totalTokens,costBrl:c.costBrl}; const logs=rj(P.usage,[]); logs.push(log); wj(P.usage,logs.slice(-1000)); res.json({answer:(resp.output_text||"Não consegui gerar uma resposta.")+`\n\n---\nInformações da IA:\nNível: ${lvl.label}\nModelo: ${model}\nTokens estimados: ${c.totalTokens}\nCusto estimado: R$ ${c.costBrl.toFixed(4)}`,usage:log,summary:usageSummary()})}catch(e){console.error(e);res.status(500).json({error:e?.message||"Erro ao conectar com OpenAI."})}});
app.use(express.static(__dirname)); app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"index.html"))); app.listen(port,()=>console.log(`\nAMX HUB ${version} STABLE\nAcesse: http://localhost:${port}\n`));
